### ISSUE TITLE
How to generate dataset.pkl and coms.tok/dats.tok/smls.tok from raw data?

### ISSUE THREAD

**Issue by meikerwang** [mcmillco/funcom#1]
Now I want to reproduce your model "ast-attendgru" on my own data,
how can I process my data such as [funcom](http://leclair.tech/data/funcom/#rawdata) into the format of model's input?
Is there some script or other code?

**Comment by acleclair** [comment]
You can find the processing scripts in our other repo [Funcom GNN](https://github.com/acleclair/ICPC2020_GNN/tree/master/processing)

**Comment by meikerwang** [comment]
thx for your reply.
