### ISSUE TITLE
How to work a subset of the dataset?

### ISSUE THREAD

**Issue by ahmedwael19** [mcmillco/funcom#2]
Is there is a way to work with a subset of the dataset and not the complete 2.1 million? 
It would be really great if so.

**Comment by mcmillco** [comment]
As a matter of fact, yes, we are working on this.  For the time being, you may of course make your own random selection of the training/val/test sets as you like.  You could randomly select 10% of each set and save a lot of training time.

**Comment by ahmedwael19** [comment]
Thanks for your prompt response!
Can you please walk me through the process? It would be really appreciated.

**Comment by mcmillco** [comment]
There is not much to explain about the process.  When you download the dataset, you will be presented with 2.1m examples, split into train/val/test sets.  You could just write a Python script to load the dataset, randomly select 10% (or whatever percent), and write that selection to another file.  Sorry that I do not have time to write all these scripts for you.
