### ISSUE TITLE
Providing requirement.txt for model reproducibility 

### ISSUE THREAD

**Issue by DRMALEK** [mcmillco/funcom#4]
Is there any way that requirement.txt can be provided? I'm struggling with Keras and TensorFlow versions, etc.
Thanks.

**Comment by acleclair** [comment]
I will work on getting a requirements.txt added. In the mean time the README states which versions of the major DL libraries it uses

"We assume Ubuntu 18.04, Python 3.6, Keras 2.2.4, TensorFlow 1.12. "
