### ISSUE TITLE
KeyError: 'dttrain' in file "train.py", line 135

### ISSUE THREAD

**Issue by z666pr** [mcmillco/funcom#5]
https://github.com/mcmillco/funcom/blob/e599de98961d8e2e2d7855bf21594be4cda22a3c/train.py#L135

Hi! I use the dataset downloaded [here](https://icse2018.s3.us-east-2.amazonaws.com/funcom.tar.gz).

The output:

![image](https://user-images.githubusercontent.com/33471339/114962699-c493b280-9e9d-11eb-8b54-ede1a97aa00a.png)

It shows that `seqdata` loaded from "funcom/data/standard/dataset.pkl" has no keys named `dttrain` but a `dtrain` instead.

![image](https://user-images.githubusercontent.com/33471339/114962662-aded5b80-9e9d-11eb-82b3-890ff13e8003.png)

Shall I change it to `dtrain` instead?

**Comment by acleclair** [comment]
Yes it should be dtrain
