### ISSUE TITLE
Raw data not available

### ISSUE THREAD

**Issue by DSOTM-pf** [mcmillco/funcom#6]
Hello, I can't download raw data from [homepage](http://leclair.tech/data/funcom).
![image](https://user-images.githubusercontent.com/26241319/129005704-1cde219c-91ed-45fe-ade0-d41ad57446b2.png)

**Comment by acleclair** [comment]
I am in the process of moving the data over to a new service and it has caused some issues. Here is a working link to the dataset download page.

http://leclair.tech/data/funcom/index_v5.html
